<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2018.1.1.386
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Envoi de Formulaire INSCRIPTION',
	'heading' => 'Envoi du nouveau formulaire',
	'success_redirect' => '',
	'resources' => array(
		'checkbox_checked' => 'Coché',
		'checkbox_unchecked' => 'Non coché',
		'submitted_from' => 'Formulaire envoyé depuis le site web :%s',
		'submitted_by' => 'Adresse IP du visiteur :%s',
		'too_many_submissions' => 'Trop d\'envois effectués récemment à partir de cette adresse IP',
		'failed_to_send_email' => 'Echec de l\'envoi du courrier électronique',
		'invalid_reCAPTCHA_private_key' => 'Clé privée reCAPTCHA non valide',
		'invalid_reCAPTCHA2_private_key' => 'Clé privée reCAPTCHA 2.0 non valide.',
		'invalid_reCAPTCHA2_server_response' => 'Réponse du serveur à l\'outil reCAPTCHA 2.0 non valide.',
		'invalid_field_type' => 'Type de champ inconnu « %s »',
		'invalid_form_config' => 'Le champ « %s » a une configuration non valide.',
		'unknown_method' => 'Méthode de requête inconnue du serveur'
	),
	'email' => array(
		'from' => '',
		'to' => ''
	),
	'fields' => array(
		'custom_U778' => array(
			'order' => 1,
			'type' => 'string',
			'label' => 'code de paiement',
			'required' => true,
			'errors' => array(
				'required' => 'Le champ « code de paiement » est obligatoire.'
			)
		),
		'Email' => array(
			'order' => 2,
			'type' => 'email',
			'label' => 'id du parrain',
			'required' => true,
			'errors' => array(
				'required' => 'Le champ « id du parrain » est obligatoire.',
				'format' => 'Le champ « id du parrain » contient une adresse électronique non valide.'
			)
		),
		'custom_U829' => array(
			'order' => 3,
			'type' => 'string',
			'label' => 'votre pseudo',
			'required' => true,
			'errors' => array(
				'required' => 'Le champ « votre pseudo » est obligatoire.'
			)
		),
		'custom_U841' => array(
			'order' => 4,
			'type' => 'string',
			'label' => 'Votre passe',
			'required' => true,
			'errors' => array(
				'required' => 'Le champ « Votre passe » est obligatoire.'
			)
		),
		'custom_U853' => array(
			'order' => 5,
			'type' => 'string',
			'label' => 'Tél. domicile',
			'required' => true,
			'errors' => array(
				'required' => 'Le champ « Tél. domicile » est obligatoire.'
			)
		),
		'custom_U865' => array(
			'order' => 6,
			'type' => 'string',
			'label' => 'VILLE',
			'required' => true,
			'errors' => array(
				'required' => 'Le champ « VILLE » est obligatoire.'
			)
		),
		'custom_U877' => array(
			'order' => 7,
			'type' => 'string',
			'label' => 'MAIL',
			'required' => true,
			'errors' => array(
				'required' => 'Le champ « MAIL » est obligatoire.'
			)
		)
	)
);

process_form($form);
?>
