<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2018.1.1.386
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Envoi de Formulaire formulaire',
	'heading' => 'Envoi du nouveau formulaire',
	'success_redirect' => '',
	'resources' => array(
		'checkbox_checked' => 'Coché',
		'checkbox_unchecked' => 'Non coché',
		'submitted_from' => 'Formulaire envoyé depuis le site web :%s',
		'submitted_by' => 'Adresse IP du visiteur :%s',
		'too_many_submissions' => 'Trop d\'envois effectués récemment à partir de cette adresse IP',
		'failed_to_send_email' => 'Echec de l\'envoi du courrier électronique',
		'invalid_reCAPTCHA_private_key' => 'Clé privée reCAPTCHA non valide',
		'invalid_reCAPTCHA2_private_key' => 'Clé privée reCAPTCHA 2.0 non valide.',
		'invalid_reCAPTCHA2_server_response' => 'Réponse du serveur à l\'outil reCAPTCHA 2.0 non valide.',
		'invalid_field_type' => 'Type de champ inconnu « %s »',
		'invalid_form_config' => 'Le champ « %s » a une configuration non valide.',
		'unknown_method' => 'Méthode de requête inconnue du serveur'
	),
	'email' => array(
		'from' => '',
		'to' => ''
	),
	'fields' => array(
		'custom_U347' => array(
			'order' => 1,
			'type' => 'string',
			'label' => 'Date de mise en terre',
			'required' => true,
			'errors' => array(
				'required' => 'Le champ « Date de mise en terre » est obligatoire.'
			)
		),
		'Email' => array(
			'order' => 2,
			'type' => 'email',
			'label' => 'Date de recolte',
			'required' => true,
			'errors' => array(
				'required' => 'Le champ « Date de recolte » est obligatoire.',
				'format' => 'Le champ « Date de recolte » contient une adresse électronique non valide.'
			)
		),
		'custom_U410' => array(
			'order' => 3,
			'type' => 'string',
			'label' => 'Stock prévisionnel',
			'required' => true,
			'errors' => array(
				'required' => 'Le champ « Stock prévisionnel » est obligatoire.'
			)
		),
		'custom_U422' => array(
			'order' => 4,
			'type' => 'string',
			'label' => 'Stock disponible',
			'required' => true,
			'errors' => array(
				'required' => 'Le champ « Stock disponible » est obligatoire.'
			)
		)
	)
);

process_form($form);
?>
